{{- range .Values.persistentVolumeClaims }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - {{ .accessMode }}
  storageClassName: {{ .storageClassName }}
  resources:
    requests:
      storage: {{ .storage }}
{{- end }}
