apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
  namespace: {{ .Release.Namespace }}
stringData:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}